#登陆相关配置
login:
  #开放的模拟登陆api服务器地址
  api: "http://www.zimo.wiki:8080/wisedu-unified-login-api-v1.0/api/login"
qmsg:
  qmsgkey: 'https://qmsg.zendee.cn/send/xxxxxxxxxxx'
#用户组配置
users:
  - user:
      #username 学号或者工号
      username: '190000001223'
      password: '190000001223'
      address: 中国xx省xx市xx区xx栋
      email: 461009747@qq.com
      school: xx学院
      lon: 114.422288
      lat: 23.038858
      abnormalReason: 在家
      qq: '12345'
  - user:
      #username 学号或者工号
      username: '190000001223'
      password: '190000001223'
      address: 中国xx省xx市xx区xx栋
      email: 461009747@qq.com
      school: xx学院
      lon: 114.422288
      lat: 23.038858
      abnormalReason: 在家
      qq: '12345'
  #多用户配置，将下面的注释去掉即可，如果有表单内容有图片，不建议使用多用户配置
#今日校园相关配置
cpdaily:
  #签到的标题，必填
  title: 健康打卡
  #是否检查问题,true检查，false不检查
  check: false
  defaults:
    - default:
       title: 你当前的状况是？
       value: 正常，没有症状 
